include_guard(GLOBAL)
if(WIN32)
    enable_language(RC)
endif()

function(picoate_component_version target version filename)
    set_target_properties(${target} PROPERTIES VERSION "${version}")
    if(WIN32)
        string(REPLACE "." "," COMPONENT_VERSION_NUMBERS "${version}.0")
        set(COMPONENT_VERSION "${version}")
        set(COMPONENT_FILENAME "${filename}")
        get_target_property(target_type ${target} TYPE)
        if(target_type STREQUAL "EXECUTABLE")
            set(COMPONENT_FILETYPE "VFT_APP")
        else()
            set(COMPONENT_FILETYPE "VFT_DLL")
        endif()
        set(resource "${CMAKE_CURRENT_BINARY_DIR}/${target}_version.rc")
        configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/WindowsVersion.rc.in" "${resource}" @ONLY)
        target_sources(${target} PRIVATE "${resource}")
    endif()
endfunction()
